wandb_version: 1

learning_rate:
  desc: null
  value: 0.001
batch_size:
  desc: null
  value: 6
conv_kernel:
  desc: null
  value: 3
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.11.8
    cli_version: 0.17.6
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1723643340
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.11.8
      5: 0.17.6
      8:
      - 1
      - 5
      13: linux-x86_64
